language: node_js
node_js: 16
cache: yarn

os: linux
dist: focal

jobs:
  fast_finish: true
  include:
    - stage: verify
      if: branch != master AND type != pull_request
      install:
        - yarn
      script:
        - yarn build
        - if [ "$CI_TEST" != "false" ]; then
          yarn test;
          fi

    - &build
      if: branch = master
      stage: build
      install:
        - yarn
      script:
        - yarn build
      # https://docs.travis-ci.com/user/using-workspaces/
      workspaces:
        create:
          name: linux-shared
          paths:
            - packages

    - <<: *build
      if: branch = master AND env(CI_WIN_BUILD) = true AND type = pull_request
      os: windows
      script: yarn build
      # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336/2
      env: YARN_GPG=no
      workspaces:
        create:
          name: win-shared
          paths:
            - packages/**/target

    - &test
      if: branch = master AND type = pull_request AND env(CI_TEST) != false
      stage: test
      script: yarn test
      workspaces:
        use: linux-shared

    - <<: *test
      node_js: 12

    - <<: *test
      node_js: 14

    - <<: *test
      if: branch = master AND type != pull_request AND env(CI_TEST) != false
      before_script:
        - if [ "$CC_TEST_REPORTER_ID" != "" ]; then
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
            chmod +x ./cc-test-reporter;
            ./cc-test-reporter before-build;
          fi
      script:
        - if [ "$CC_TEST_REPORTER_ID" != "" ]; then
            yarn test:report;
          else
            yarn test;
          fi
      after_script:
        - if [ "$CC_TEST_REPORTER_ID" != "" ]; then
            ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info;
            ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT;
          fi

    - <<: *test
      if: branch = master AND type = pull_request AND env(CI_WIN_BUILD) = true AND env(CI_TEST) != false
      os: windows
      env: YARN_GPG=no
      install: yarn
      workspaces:
        use: win-shared

    - <<: *test
      if: branch = master AND type = pull_request AND env(CI_WIN_BUILD) = true AND env(CI_TEST) != false
      os: windows
      node_js: 12
      install: yarn
      env: YARN_GPG=no
      workspaces:
        use: win-shared

    - stage: release
      if: branch = master AND type != pull_request AND env(CI_RELEASE) = true
      workspaces:
        use: linux-shared
      script: npx -p @qiwi/semrel-toolkit multi-semrel
